[settings]
experimental = true
python.uv_venv_auto = true

[tools]
rust = { version = "latest", profile = "default" }
"aqua:cargo-bins/cargo-binstall" = "latest"
mkcert = "latest"
uv = "latest"
"aqua:rust-cross/cargo-zigbuild" = "latest"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
zig = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:protocolbuffers/protobuf/protoc" = "latest"
node = "20"

[env]
_.file = ".env"
