[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
exclude = ["test_files/*", "python", "*.py", "pyproject.toml", "*.js", "*.ts", "node", "package.json", "examples/images/*", "mkdocs.yml", "docs/*", "tests/*", ".github", "Dockerfile", "docs"]
version = "0.1.0"

[workspace.dependencies]
# Text splitting - the main crate we'll use
text-splitter = { version = "0.27", features = [
  "code",
  "tiktoken-rs",
  "tokenizers",
] }
tiktoken-rs = "0.7"

# Tokenization
tokenizers = { version = "0.21", features = ["http"] }

tokio = { version = "1", features = ["rt", "macros", "fs", "sync"] }
tracing = "0.1.41"

# Tree-sitter parsers (individual crates for all languages)
tree-sitter = "0.25"
tree-sitter-python = "0.23"
tree-sitter-javascript = "0.23"
tree-sitter-typescript = "0.23"
tree-sitter-java = "0.23"
tree-sitter-cpp = "0.23"
tree-sitter-c = "0.24"
tree-sitter-c-sharp = "0.23"
tree-sitter-go = "0.23"
tree-sitter-rust = "0.24"
tree-sitter-ruby = "0.23"
# tree-sitter-php = "0.23"  # PHP breaks everything
tree-sitter-swift = "0.7"
tree-sitter-kotlin = "0.3"
tree-sitter-scala = "0.24"
tree-sitter-sql = "0.0.2"
tree-sitter-bash = "0.25"
tree-sitter-r = "1.2"

# Python bindings
pyo3 = { version = "0.25.1", features = ["extension-module", "abi3-py39"] }
pyo3-async-runtimes = { version = "0.25.0", features = ["tokio-runtime"] }
pyo3-log = "0.12.0"

# Async runtime
tokio = { version = "1", features = ["rt", "macros", "fs", "sync"] }

# Error handling
thiserror = "2.0"

# Utils
log = "0.4"
tree-sitter-language = "0.1.5"

[profile.dev]
rpath = true

[profile.release]
rpath = true
