[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
# Text splitting - the main crate we'll use
text-splitter = { version = "0.27", features = [
  "code",
  "tiktoken-rs",
  "tokenizers",
] }

# Tokenization
tokenizers = { version = "0.21", features = ["http"] }
tiktoken-rs = "0.7"

# Tree-sitter parsers (individual crates for all languages)
tree-sitter = "0.25"
tree-sitter-language = "0.1.5"

tokio = { version = "1", features = ["rt", "macros", "fs", "sync"] }