FROM rust:alpine

RUN apk add --no-cache \
    build-base \
    openssl-dev \
    openssl-libs-static \
    musl-dev \
    libffi-dev \
    python3 \
    py3-pip \
    uv \
    nodejs \
    npm \
    git \
    zig \
    gcc \
    g++ \
    make \
    pkgconf \
    mold \
    bash \
    clang\
    curl \
    protobuf-dev

RUN cargo install cargo-zigbuild
