#!/usr/bin/env bash
#MISE description="Build the breeze binary, Python wheels and NAPI bindings"

proj_dir=$(git rev-parse --show-toplevel)


cargo zigbuild --release --workspace --exclude breeze-py --exclude breeze-napi
cd "$proj_dir/crates/breeze-py" && maturin develop --release
cd "$proj_dir/crates/breeze-napi" && npm run build
