#!/usr/bin/env bash
#MISE description="Test the breeze application, Python wheels and NAPI bindings"

proj_dir=$(git rev-parse --show-toplevel)

cargo nextest run --no-fail-fast --features local-embeddings
cd "$proj_dir/crates/breeze-py" && uv run --active pytest -v
cd "$proj_dir/crates/breeze-napi" && npm install && npm run test:all
