[package]
name = "breeze"
version = "0.1.0"
edition = "2024"

[dependencies]
breeze-chunkers = { path = "../breeze-chunkers" }
arrow = { version = "55.1.0", features = ["prettyprint"] }
arrow_convert = "0.9.0"
lancedb = { version = "0.20.0" }
serde = "1"
serde_arrow = "0.13.4"
uuid = { version = "1", features = ["v7", "serde", "zerocopy"] }
chrono = { version = "0.4", features = ["serde"] }
blake3 = { version = "1.8.2", features = ["serde"] }
tokio = { workspace = true }
pretty_env_logger = "0.5.0"
futures-util = "0.3.31"
async-trait = "0.1.88"
