[package]
name = "breeze"
version = "0.1.0"
edition = "2024"

[features]
default = []
cuda = ["embed_anything/cuda"]
cudnn = ["embed_anything/cudnn"]
mkl = ["embed_anything/mkl"]
accelerate = ["embed_anything/accelerate"]
metal = ["embed_anything/metal"]
flash-attn = ["embed_anything/flash-attn"]

[dependencies]
anyhow = "1.0"
arrow = { version = "55.1.0", features = ["prettyprint"] }
arrow_convert = "0.9.0"

# Embedding providers
async-openai = "0.28"
async-stream = "0.3"
async-trait = "0.1.88"
blake3 = { version = "1.8.2", features = ["serde"] }
breeze-chunkers = { path = "../breeze-chunkers" }
chrono = { version = "0.4", features = ["serde"] }

# Configuration and CLI
clap = { version = "4.5", features = ["derive", "env"] }
config = "0.15"
console-subscriber = "0.4.1"
embed_anything = { version = "0.6.4", features = ["ort"] }
flume = "0.11"
futures = "0.3.31"
futures-util = "0.3.31"
governor = "0.10"
http = "1.2"

hyperpolyglot = "0.1.7"     # Language detection
ignore = { version = "0.4.23", features = ["simd-accel"] }
infer = "0.19.0"            # File type detection
lancedb = { version = "0.20.0" }

num_cpus = "1"
rand = "0.9"
reqwest = { version = "0.12", features = ["json", "stream"] }
reqwest-middleware = { version = "0.4.2", features = ["http2", "json", "rustls-tls"] }
reqwest-retry = "0.7"
reqwest-tracing = "0.5"
retry-policies = "0.5"
serde = { version = "1", features = ["derive"] }
serde_arrow = "0.13.4"
serde_json = "1.0"

# Error handling
thiserror = "2.0"
tokenizers = "0.21"
tokio = { workspace = true }
tokio-stream = "0.1"

# Rate limiting and utilities
tokio-util = { version = "0.7", features = ["rt"] }
toml = "0.8"
tower = "0.5"

tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["v7", "serde", "zerocopy"] }

[dev-dependencies]
tempfile = "3.11"
