name: 'Setup Build Environment'
description: 'Sets up the complete build environment for breeze-rustle'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  rust-target:
    description: 'Rust target triple to install (optional)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:

    - name: Install mold linker and C++ libraries on Linux
      if: runner.os == 'Linux'
      run: |
        # We need to ensure that all the C++ uses the same standard library
        # Install the same LLVM as the one used by the Zig toolchain
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main" | sudo tee /etc/apt/sources.list.d/llvm-19.list
        sudo apt-get update
        sudo apt-get install -y mold libssl-dev pkg-config libc++-19-dev libc++abi-19-dev clang-19
        ARCH=$(uname -m)
        echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV
        echo "CC=clang-19" >> $GITHUB_ENV
        echo "CXX=clang++-19" >> $GITHUB_ENV
        echo "CXXSTDLIB=c++" >> $GITHUB_ENV
        if [ "$ARCH" = "aarch64" ]; then
          if [[ ! -e /usr/lib/aarch64-linux-gnu/libc++.so ]] || [[ -L /usr/lib/aarch64-linux-gnu/libc++.so && ! -e /usr/lib/aarch64-linux-gnu/libc++.so ]]; then
            sudo ln -sf /usr/lib/aarch64-linux-gnu/libc++.so.1 /usr/lib/aarch64-linux-gnu/libc++.so
          fi

          echo "Setting ARM64-specific environment variables"
          echo "CFLAGS=-I/usr/include -I/usr/include/aarch64-linux-gnu" >> $GITHUB_ENV
          echo "RUSTFLAGS=-L/usr/lib/aarch64-linux-gnu" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        experimental: true
        install: false

    - name: Install tools with mise
      run: mise install
      shell: bash
      env:
        MISE_PYTHON_UV_VENV_CREATE_ARGS: "--python python${{ inputs.python-version }}"
        GITHUB_TOKEN: ${{ github.token }}


    - name: Download and setup ONNX Runtime on Linux
      if: runner.os == 'Linux'
      run: |
        # Download ONNX Runtime
        ONNX_VERSION="1.22.0"
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          ONNX_ARCH="x64"
        elif [ "$ARCH" = "aarch64" ]; then
          ONNX_ARCH="aarch64"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi

        wget -q https://github.com/microsoft/onnxruntime/releases/download/v${ONNX_VERSION}/onnxruntime-linux-${ONNX_ARCH}-${ONNX_VERSION}.tgz
        tar -xzf onnxruntime-linux-${ONNX_ARCH}-${ONNX_VERSION}.tgz

        # Set environment variables
        echo "ORT_LIBRARY_PATH=$PWD/onnxruntime-linux-${ONNX_ARCH}-${ONNX_VERSION}/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$PWD/onnxruntime-linux-${ONNX_ARCH}-${ONNX_VERSION}/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Download Qwen3 ONNX model for testing
      if: runner.os == 'Linux'
      run: |

        # Download the Qwen3 ONNX model to ensure complete files are available
        echo "Downloading Qwen3 ONNX model..."
        uvx --from 'huggingface_hub[cli]' huggingface-cli download onnx-community/Qwen3-Embedding-0.6B-ONNX
        echo "Qwen3 model download completed"
      shell: bash

    - name: Install npm dependencies
      run: npm install
      shell: bash

    - name: Install maturin
      run: |
        uv pip install --python .venv maturin[patchelf]
      shell: bash

    - name: Install Rust target
      if: inputs.rust-target != ''
      run: rustup target add ${{ inputs.rust-target }}
      shell: bash
