name: 'Setup Build Environment'
description: 'Sets up the complete build environment for breeze-rustle'

runs:
  using: 'composite'
  steps:
    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        version: latest
        install: true

    - name: Install tools with mise
      run: mise install
      shell: bash
      env:
        MISE_PYTHON_UV_VENV_CREATE_ARGS: "--python python${{ matrix.python-version }}"

    - name: Install npm dependencies
      run: npm install
      shell: bash

    # - name: Create virtual environment with specific Python version
    #   run: uv venv --python python${{ matrix.python-version }}
    #   shell: bash

    - name: Install maturin
      run: |
        uv pip install --python .venv maturin[patchelf]
      shell: bash
