name: 'Setup Build Environment'
description: 'Sets up the complete build environment for breeze-rustle'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install npm dependencies
      run: npm install
      shell: bash
    
    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "25.x"
    
    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: nextest
    
    - name: Install cargo-zigbuild
      run: cargo install cargo-zigbuild
      shell: bash