name: 'Setup Build Environment'
description: 'Sets up the complete build environment for breeze-rustle'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        experimental: true
        install: false

    - name: Install tools with mise
      run: mise install
      shell: bash
      env:
        MISE_PYTHON_UV_VENV_CREATE_ARGS: "--python python${{ inputs.python-version }}"

    - name: Install mold linker and C++ libraries on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y mold libc++-dev libc++abi-dev libstdc++-14-dev g++-14
      shell: bash

    - name: Install npm dependencies
      run: npm install
      shell: bash

    # - name: Create virtual environment with specific Python version
    #   run: uv venv --python python${{ matrix.python-version }}
    #   shell: bash

    - name: Install maturin
      run: |
        uv pip install --python .venv maturin[patchelf]
      shell: bash
