[package]
name = "breeze-chunkers"
version = "0.1.0"
edition = "2024"

[dependencies]
breeze-grammars = { path = "../breeze-grammars" }
text-splitter = { workspace = true }

tokio = { version = "1", features = ["rt", "macros", "fs", "sync"] }

# Tokenization
tokenizers = { workspace = true }
tiktoken-rs = { workspace = true }

# Tree-sitter parsers (individual crates for all languages)

tree-sitter = { workspace = true }
tree-sitter-language = { workspace = true }
tree-sitter-python = "0.23"
tree-sitter-javascript = "0.23"
tree-sitter-typescript = "0.23"
tree-sitter-java = "0.23"
tree-sitter-cpp = "0.23"
tree-sitter-c = "0.24"
tree-sitter-c-sharp = "0.23"
tree-sitter-go = "0.23"
tree-sitter-rust = "0.24"
tree-sitter-ruby = "0.23"
# tree-sitter-php = "0.23"  # PHP breaks everything
tree-sitter-swift = "0.7"
# tree-sitter-kotlin = "0.3"  # Uses incompatible tree-sitter 0.19
tree-sitter-scala = "0.24"
# tree-sitter-sql = "0.0.2"    # Uses incompatible tree-sitter 0.20
tree-sitter-bash = "0.25"
tree-sitter-r = "1.2"

# Error handling
thiserror = "2.0"

# Project walker
ignore = "0.4"              # Gitignore-aware traversal
futures = "0.3"             # Async streams
hyperpolyglot = "0.1.7"     # Language detection
infer = "0.19.0"            # File type detection
tokio-stream = "0.1"        # Async streaming
async-stream = "0.3"        # Async stream macros

[dev-dependencies]
tempfile = "3.11"          # Temporary file handling